@ECHO OFF
REM Gradle startup script for Windows generated by Crosswake.
REM This baseline is host-owned and scaffolded once.

SET APP_HOME=%~dp0
java -jar "%APP_HOME%gradle\wrapper\gradle-wrapper.jar" %*
