# crosswake:native-controls-ui template_version=1
#
# Host-owned copy generated by `mix crosswake.gen.native_controls_ui`.
# You own this file outright: Crosswake will never rewrite it, and
# re-running the generator reuses it rather than clobbering it.

defmodule CrosswakeExampleWeb.CrosswakeFallbacks do
  @moduledoc """
  Host-owned, brand-tokenized fallback UI for controls Crosswake has no native
  bridge command for.

  ## The confirm modal has no native counterpart, and never will

  `REQUIREMENTS.md` places a native alert/confirm bridge family permanently
  out of scope. This is not a fallback that degrades from something better —
  it is the primary, only, permanent confirm surface on every platform. It
  makes zero `Crosswake.Bridge` calls: no push, no `ref`, no `resolve/2`, no
  denial branch.

  If you can offer undo instead of asking "are you sure?", offer undo instead
  of this modal (Nielsen Norman Group).

  ## Why this is a `Phoenix.Component`, never a `Phoenix.LiveComponent`

  A `Phoenix.LiveComponent`'s private assigns are built from
  `Map.take([:conn_session, :root_view])` — `Crosswake.Bridge.resolve/2` would
  raise `Crosswake.Bridge.NotMountedError` inside one. This module stays a
  plain `Phoenix.Component`, never a `LiveComponent`, so any future bridge-
  aware sibling component in this same file (an `action_menu/1`, for example)
  never trips that trap either.

  ## Why not `<dialog>` / `showModal()` or the Popover API

  Both are JS-only, forcing either a second library module or an inline
  `<script>` — regressing this project's CSP posture — and both are ahead of
  this project's browser floor (`<dialog>` needs iOS 15.4, the Popover API
  needs iOS 17; the floor is iOS 15.0).

  ## Ownership

  Generated by `mix crosswake.gen.native_controls_ui`. You own this file
  outright — Crosswake will never rewrite it. Re-running the generator only
  fills in what's missing; it never overwrites an existing copy.
  """
  use Phoenix.Component

  alias Phoenix.LiveView.JS

  @doc """
  A confirm modal, rendered from a snapshot assign in the same server
  round-trip that opens it.

  Visibility is a pure function of `open` — never client-revealed, never
  triggered by a shell denial. Focus is trapped for free by
  `Phoenix.Component.focus_wrap/1`; zero JavaScript ships with this
  component.

  `title` and `confirm_label` are required with no default — a missing value
  is a compile error, not a habituating "OK"/"Confirm".
  """
  attr :id, :string, required: true
  attr :title, :string, required: true
  attr :confirm_label, :string, required: true
  attr :body, :string, default: nil
  attr :open, :boolean, default: false
  attr :pending, :boolean, default: false
  attr :error, :string, default: nil

  def confirm_modal(assigns) do
    ~H"""
    <div
      :if={@open}
      id={@id}
      class="cw-fallback"
      data-cw-fallback
      data-cw-fallback-tone="neutral"
      role="dialog"
      aria-modal="true"
      aria-labelledby={"#{@id}-title"}
      phx-window-keydown={JS.push("crosswake_fallback_dismiss")}
      phx-key="escape"
      phx-mounted={JS.focus(to: "##{@id}-action")}
      phx-remove={JS.pop_focus()}
    >
      <.focus_wrap
        id={"#{@id}-trap"}
        class="cw-fallback-panel"
        phx-click-away={JS.push("crosswake_fallback_dismiss")}
      >
        <h2 id={"#{@id}-title"} class="cw-fallback-title">{@title}</h2>

        <div class="cw-fallback-scroll">
          <p :if={@body} class="cw-fallback-body-copy">{@body}</p>
          <p :if={@error} role="alert" class="cw-fallback-error">{@error}</p>
        </div>

        <div class="cw-fallback-actions">
          <button
            type="button"
            class="cw-fallback-cancel"
            phx-click={JS.push("crosswake_fallback_dismiss")}
          >
            Cancel
          </button>
          <button
            type="button"
            id={"#{@id}-action"}
            class="cw-fallback-action"
            phx-click={JS.push("crosswake_fallback_answer")}
            phx-value-answer="confirm"
            disabled={@pending}
          >
            {if @pending, do: "Approving…", else: @confirm_label}
          </button>
        </div>
      </.focus_wrap>
    </div>
    """
  end
end
