# crosswake:native-controls-ui template_version=2
#
# Host-owned copy generated by `mix crosswake.gen.native_controls_ui`.
# You own this file outright: Crosswake will never rewrite it, and
# re-running the generator reuses it rather than clobbering it.

defmodule CrosswakeExampleWeb.CrosswakeFallbacks do
  @moduledoc """
  Host-owned, brand-tokenized fallback UI for controls Crosswake has no native
  bridge command for.

  ## The confirm modal has no native counterpart, and never will

  `REQUIREMENTS.md` places a native alert/confirm bridge family permanently
  out of scope. This is not a fallback that degrades from something better —
  it is the primary, only, permanent confirm surface on every platform. It
  makes zero `Crosswake.Bridge` calls: no push, no `ref`, no `resolve/2`, no
  denial branch.

  If you can offer undo instead of asking "are you sure?", offer undo instead
  of this modal (Nielsen Norman Group).

  ## Why this is a `Phoenix.Component`, never a `Phoenix.LiveComponent`

  A `Phoenix.LiveComponent`'s private assigns are built from
  `Map.take([:conn_session, :root_view])` — the bridge's `resolve/2` function
  would raise `Crosswake.Bridge.NotMountedError` inside one. This module stays a
  plain `Phoenix.Component`, never a `LiveComponent`, so any future bridge-
  aware sibling component in this same file never trips that trap either.

  ## Why not `<dialog>` / `showModal()` or the Popover API

  Both are JS-only, forcing either a second library module or an inline
  `<script>` — regressing this project's CSP posture — and both are ahead of
  this project's browser floor (`<dialog>` needs iOS 15.4, the Popover API
  needs iOS 17; the floor is iOS 15.0).

  ## `aria-modal` + VoiceOver — a recorded, unproven limitation

  `aria-modal="true"` is unreliable in Safari combined with VoiceOver (the
  reason React Aria ships `ariaHideOutside`). The server-rendered `inert`
  attribute LiveView's focus trap relies on is *believed* to mitigate the gap
  for free, but that belief is explicitly **not proven** by this phase's proof
  lane. Treat it as a manual-check limitation, never as a passing assertion,
  until someone verifies it by hand with a screen reader.

  ## Ownership

  Generated by `mix crosswake.gen.native_controls_ui`. You own this file
  outright — Crosswake will never rewrite it. Re-running the generator only
  fills in what's missing; it never overwrites an existing copy.
  """
  use Phoenix.Component

  alias Phoenix.LiveView.JS

  @doc """
  A confirm modal, rendered from a snapshot assign in the same server
  round-trip that opens it.

  Visibility is a pure function of `open` — never client-revealed, never
  triggered by a shell denial. Focus is trapped for free by
  `Phoenix.Component.focus_wrap/1`; zero JavaScript ships with this
  component.

  `title` and `confirm_label` are required with no default — a missing value
  is a compile error, not a habituating "OK"/"Confirm".

  ## Tones

  `tone: :neutral` (the default) renders `role="dialog"`, allows click-away
  dismissal, and sets initial focus on the action button.

  `tone: :destructive` renders `role="alertdialog"`, allows **no** click-away
  dismissal (the Radix Dialog/AlertDialog split shadcn also inherits), and
  sets initial focus on Cancel instead — the one tone branch this component
  makes. Destructive tone also **requires** `body`: the component DSL has no
  way to express a conditionally-required attr, so a destructive confirm with
  a blank `body` raises at render instead of silently shipping a missing
  consequence sentence.

      <.confirm_modal
        id="delete-job-confirm"
        tone={:destructive}
        title="Delete this job?"
        body="This removes the job and its 3 photos. It cannot be undone."
        confirm_label="Delete job"
        open={@delete_confirm_open}
      />
  """
  attr :id, :string, required: true
  attr :title, :string, required: true
  attr :confirm_label, :string, required: true
  attr :body, :string, default: nil
  attr :tone, :atom, values: [:neutral, :destructive], default: :neutral
  attr :open, :boolean, default: false
  attr :pending, :boolean, default: false
  attr :error, :string, default: nil

  def confirm_modal(assigns) do
    if assigns.tone == :destructive and blank?(assigns[:body]) do
      raise ArgumentError, """
      confirm_modal/1: tone=:destructive requires the `body` attr.

      The destructive confirm's consequence sentence can never be missing —
      pass `body="..."` naming exactly what will happen and that it cannot be
      undone.
      """
    end

    ~H"""
    <div
      :if={@open}
      id={@id}
      class="cw-fallback"
      data-cw-fallback
      data-cw-fallback-tone={@tone}
      data-cw-fallback-surface="confirm"
      role={if @tone == :destructive, do: "alertdialog", else: "dialog"}
      aria-modal="true"
      aria-labelledby={"#{@id}-title"}
      phx-window-keydown={JS.push("crosswake_fallback_dismiss")}
      phx-key="escape"
      phx-mounted={
        JS.focus(to: if(@tone == :destructive, do: "##{@id}-cancel", else: "##{@id}-action"))
      }
      phx-remove={JS.pop_focus()}
    >
      <.focus_wrap
        id={"#{@id}-trap"}
        class="cw-fallback-panel"
        phx-click-away={if @tone == :neutral, do: JS.push("crosswake_fallback_dismiss")}
      >
        <h2 id={"#{@id}-title"} class="cw-fallback-title">{@title}</h2>

        <div class="cw-fallback-scroll">
          <p :if={@body} class="cw-fallback-body-copy">{@body}</p>
          <p :if={@error} role="alert" class="cw-fallback-error">{@error}</p>
        </div>

        <div class="cw-fallback-actions">
          <button
            type="button"
            id={"#{@id}-cancel"}
            class="cw-fallback-cancel"
            phx-click={JS.push("crosswake_fallback_dismiss")}
          >
            Cancel
          </button>
          <button
            type="button"
            id={"#{@id}-action"}
            class={["cw-fallback-action", @tone == :destructive && "cw-fallback-action-danger"]}
            phx-click={JS.push("crosswake_fallback_answer")}
            phx-value-answer="confirm"
            disabled={@pending}
          >
            {confirm_action_label(@tone, @pending, @confirm_label)}
          </button>
        </div>
      </.focus_wrap>
    </div>
    """
  end

  @doc """
  The inline fail-closed alert — renders when a control this phase covers is
  unavailable, WITHOUT ever opening a modal.

  Rendered in normal document flow (not inside `.cw-fallback`), `role="alert"`,
  no fixed height, never scrolling or clipping — a clipped denial would read
  as silent degradation.

  `kind: :stale_binary` and `kind: :undeclared` render one of two fixed,
  literal strings with no interpolated values — maximum length is known at
  author time. `kind: :shell_unreachable` renders nothing at all: there is no
  honest string for "no shell is present at all" (precedent: the haptics
  `:shell_unreachable` branch in `approval_live.ex`).

      <.fallback_alert :if={@fallback_denied} kind={@fallback_denial_kind} />
  """
  attr :kind, :atom, required: true, values: [:stale_binary, :undeclared, :shell_unreachable]

  def fallback_alert(assigns) do
    ~H"""
    <p
      :if={@kind != :shell_unreachable}
      role="alert"
      class="cw-fallback-inline-alert"
      data-cw-fallback-alert={@kind}
    >
      {fallback_alert_message(@kind)}
    </p>
    """
  end

  @doc """
  An action menu — a centred modal listing allowlisted actions, reusing the
  same panel chassis as `confirm_modal/1` (one object, one a11y contract).

  This is the one real fallback in this phase, but it pushes nothing: the
  bridge's `push/3` function is never called anywhere in this file, and no
  bridge command exists for it (D-01). Selecting a row or dismissing the
  menu round-trips through your own `handle_event` clauses instead — see
  "Paste-ready handle_event clauses" below.

  ## Structure and signal (D-20)

  A mandatory `<h2>` heading, a `<ul>`/`<li>`/`<button>` list, and **no
  icons** — shape, colour, and text carry all signal. Rows scroll inside
  `max-height: min(60vh, 420px)` once there are enough of them; the heading
  and Cancel stay outside that scroll container so both are reachable at any
  row count. A `destructive: true` row always renders last, behind a 4px gap
  band with a 3px left bar — this component reorders `actions` itself, so
  the destructive row is last regardless of the order you pass it in.

  ## `actions` — the frozen shape (D-53, one-way door)

  `actions :: [%{id: String.t() | nil, label: String.t(), destructive: boolean(), icon: nil}]`

  Frozen by a dedicated planning checkpoint (`155-06-PLAN.md` Task 1) exactly
  as `UX-CONTRACT.md:41` records it, because this file is host-owned and
  never regenerated — getting the shape wrong means hand-editing it in every
  adopter's app. `icon` is a **reserved, deliberately unrendered** key: D-20
  bans icons in this phase, but reserving the key now costs one unrendered
  field and saves a hand-edit in every adopter app the day a future phase
  wants it (see the Phase 156 hand-off comment inside this function's own
  `~H` block).

  A row whose `id` is `nil` renders **disabled**, with `label` carrying its
  own reason inline (see the disabled-row string in the phase's copywriting
  contract, e.g. `"Reassign job — needs a supervisor"`) — never a silently
  greyed control, never omitted from the list.

  Selecting an enabled row emits `select-with-id`; dismissing emits
  `dismiss` — there is no third outcome. A destructive row's click does
  **not** emit a mutation directly; route it through your own
  `confirm_modal` first (see the handler recipe below).

  ## ARIA (D-21) — deliberately not the APG `menu` role

  The APG Menu contract obliges roving tabindex, arrow-key navigation,
  Home/End, and Tab-closes — the exact JavaScript this phase exists to
  avoid. Declaring that contract without honoring it is worse than never
  claiming it: "no ARIA is better than bad ARIA." This is buttons in a
  dialog, not a native menu role — this file never sets a `role` attribute
  to that value, and never sets the ARIA popup-trigger attribute either.
  Render your own trigger button — this component never renders one — and
  pair it with this menu's `id` using `aria-expanded` and `aria-controls`
  instead:

      <button
        type="button"
        id={@trigger_id}
        aria-expanded={@menu_open}
        aria-controls="record-actions-menu"
        phx-click="open_action_menu"
      >
        Actions
      </button>

      <.action_menu
        id="record-actions-menu"
        trigger_id={@trigger_id}
        open={@menu_open}
        actions={@actions}
      />

  `trigger_id` is used by this component only to return focus to your
  trigger when the menu closes — it does not render anything on its own.

  ## Pending (D-20)

  `pending` disables every row and Cancel, but renders no per-row pending
  text or spinner — a per-row pending state would need the icons this phase
  bans. Render your own pending affordance on the trigger button instead
  (e.g. `phx-disable-with`).

  ## Paste-ready handle_event clauses

  Fixed event names, shared with `confirm_modal/1`:
  `crosswake_fallback_answer` disambiguates by payload shape (`%{"answer" =>
  "confirm"}` for a confirm modal vs. `%{"id" => id}` for a menu row);
  `crosswake_fallback_dismiss` is shared verbatim — merge the menu's open
  assign into the same clause you already pasted for `confirm_modal/1`.

      def handle_event("crosswake_fallback_answer", %{"id" => id}, socket) do
        socket = Crosswake.Bridge.resolve(socket, :menu)
        # TODO: look up the action for `id` and run its mutation. Route a
        # destructive selection through your own confirm_modal first —
        # never straight to the mutation.
        {:noreply, assign(socket, menu_open: false)}
      end

      def handle_event("crosswake_fallback_dismiss", _params, socket) do
        socket = Crosswake.Bridge.resolve(socket, :menu)
        {:noreply, assign(socket, confirm_open: false, menu_open: false)}
      end

  Both handlers call `resolve/2` exactly once — it is the only dedup
  mechanism (D-25). Never route a native reply and this click into the same
  event name to "deduplicate" them a second way; that guarantees the same
  mutation runs twice.
  """
  attr :id, :string, required: true
  attr :trigger_id, :string, required: true
  attr :open, :boolean, default: false
  attr :heading, :string, default: "Choose an action"
  attr :actions, :list, required: true
  attr :pending, :boolean, default: false

  def action_menu(assigns) do
    assigns = assign(assigns, :ordered_actions, order_menu_actions(assigns.actions))

    ~H"""
    
    <div
      :if={@open}
      id={@id}
      class="cw-fallback"
      data-cw-fallback
      data-cw-fallback-tone="neutral"
      data-cw-fallback-surface="menu"
      role="dialog"
      aria-modal="true"
      aria-labelledby={"#{@id}-heading"}
      phx-window-keydown={JS.push("crosswake_fallback_dismiss")}
      phx-key="escape"
      phx-mounted={JS.focus(to: "##{@id}-cancel")}
      phx-remove={JS.focus(to: "##{@trigger_id}") |> JS.pop_focus()}
    >
      <.focus_wrap
        id={"#{@id}-trap"}
        class="cw-fallback-panel"
        phx-click-away={JS.push("crosswake_fallback_dismiss")}
      >
        <h2 id={"#{@id}-heading"} class="cw-fallback-title">{@heading}</h2>

        <div class="cw-fallback-scroll">
          <ul :if={@ordered_actions != []} class="cw-fallback-menu-list">
            <li
              :for={{action, gap?} <- @ordered_actions}
              class={["cw-fallback-menu-item", gap? && "cw-fallback-menu-item-gap"]}
            >
              <button
                type="button"
                class={["cw-fallback-menu-row", action.destructive && "cw-fallback-menu-row-danger"]}
                disabled={@pending or menu_row_disabled?(action)}
                phx-click={JS.push("crosswake_fallback_answer")}
                phx-value-id={action.id}
              >
                {action.label}
              </button>
            </li>
          </ul>

          <p :if={@ordered_actions == []} class="cw-fallback-menu-empty">
            No actions are available for this record.
          </p>
        </div>

        <div class="cw-fallback-actions cw-fallback-actions-menu">
          <button
            type="button"
            id={"#{@id}-cancel"}
            class="cw-fallback-cancel"
            phx-click={JS.push("crosswake_fallback_dismiss")}
            disabled={@pending}
          >
            Cancel
          </button>
        </div>
      </.focus_wrap>
    </div>
    """
  end

  # ---------------------------------------------------------------------------
  # Copy (D-09 — no internal vocabulary reaches any of these strings)
  # ---------------------------------------------------------------------------

  defp confirm_action_label(:destructive, true, _confirm_label), do: "Deleting…"
  defp confirm_action_label(:destructive, false, confirm_label), do: confirm_label
  defp confirm_action_label(:neutral, true, _confirm_label), do: "Approving…"
  defp confirm_action_label(:neutral, false, confirm_label), do: confirm_label

  defp fallback_alert_message(:stale_binary) do
    "This action needs a newer version of the app. Update the app, then try again."
  end

  defp fallback_alert_message(:undeclared) do
    "This action isn't available here. Nothing was changed."
  end

  defp blank?(nil), do: true
  defp blank?(""), do: true
  defp blank?(_value), do: false

  # ---------------------------------------------------------------------------
  # Menu row ordering (D-20 — destructive always last, gap band on the first)
  # ---------------------------------------------------------------------------

  # Returns [{action, gap?}] with every destructive action moved after every
  # non-destructive one (order within each group preserved), regardless of
  # the order `actions` was passed in. `gap?` is true only for the first
  # destructive row when at least one non-destructive row precedes it — that
  # is the one row that needs the 4px separation band.
  defp order_menu_actions(actions) do
    {destructive, rest} = Enum.split_with(actions, & &1.destructive)

    tagged_rest = Enum.map(rest, &{&1, false})

    tagged_destructive =
      case {destructive, rest} do
        {[], _rest} -> []
        {[first | remaining], []} -> [{first, false} | Enum.map(remaining, &{&1, false})]
        {[first | remaining], _rest} -> [{first, true} | Enum.map(remaining, &{&1, false})]
      end

    tagged_rest ++ tagged_destructive
  end

  # An action with no `id` cannot emit a valid select-with-id outcome — this
  # is how a present-but-not-currently-permitted action is represented
  # without adding a field to the frozen `actions` shape (D-53). `label` is
  # expected to already carry the reason inline, per the phase's
  # copywriting contract (e.g. "Reassign job — needs a supervisor").
  defp menu_row_disabled?(%{id: nil}), do: true
  defp menu_row_disabled?(_action), do: false
end
