import { test, expect, type Page } from '@playwright/test';

/*
 * Phase 155 Plan 01, Task 1 — the tracer's browser proof.
 *
 * This spec proves ONE path end-to-end: a confirm modal, generated by the real
 * `mix crosswake.gen.native_controls_ui` task from real library templates and
 * committed at `examples/phoenix_host/lib/crosswake_example_web/components/
 * crosswake_fallbacks.ex`, renders on a real product route
 * (`/saas/approvals/approval-1`) in Chromium with a resolved scrim.
 *
 * HONEST LABELLING (house style — see `evidence_panel.spec.ts`'s moduledoc and
 * `Crosswake.Bridge.CatalogGuard`'s six-criteria docblock).
 *
 *   A1 — MECHANICAL. `[data-cw-fallback]` is absent before the trigger click and
 *        present (count 1, `role="dialog"`) after it — an absent-before/
 *        present-after pair, not a bare present-after assertion. Non-vacuous
 *        because the rendered file is the real generator output committed to
 *        this repo, carrying the `crosswake:native-controls-ui` stamp — this
 *        spec asserts that stamp is present so a hand-written stand-in can
 *        never satisfy it silently.
 *   A2 — MECHANICAL. The panel's computed backdrop is asserted non-transparent
 *        (the D-29 canary): `compile-tokens.js`'s `groups` array must list
 *        `overlay` or `--cw-overlay-scrim` resolves to nothing and the scrim
 *        renders fully transparent with no other test failure — this is the
 *        one assertion that would catch that silent drop.
 *
 * NOT claimed by this file: full contrast/theme coverage, the focus-trap
 * behavior contract, the destructive tone, the action menu, or any of the
 * three-condition PROOF-01 lane (undeclared/no-silence) — those are Plan
 * 155-07's job. This spec is the tracer's single path only.
 */

const A1_ROUTE = '/saas/approvals/approval-1';
const FALLBACK = '[data-cw-fallback]';
const GENERATED_COMPONENT_PATH =
  'lib/crosswake_example_web/components/crosswake_fallbacks.ex';

test.describe('Phase 155 native-controls fallback — tracer proof', () => {
  test('A1: the generated confirm modal is absent before the trigger, present with a resolved scrim after', async ({
    page,
  }) => {
    await resetShowcase(page);
    await asApprover(page);

    await page.goto(A1_ROUTE);

    // Absent before — not a bare present-after assertion.
    await expect(page.locator(FALLBACK)).toHaveCount(0);

    await page.getByRole('button', { name: 'Preview the confirm fallback' }).click();

    const fallback = page.locator(FALLBACK);
    await expect(fallback).toHaveCount(1);
    await expect(fallback).toHaveAttribute('role', 'dialog');
    await expect(fallback).toHaveAttribute('data-cw-fallback-tone', 'neutral');
    await expect(fallback).toHaveAttribute('aria-modal', 'true');

    // D-29 canary: the scrim token resolved to a real, non-transparent color —
    // not `rgba(0, 0, 0, 0)` / `transparent`, which is what a silently-dropped
    // `--cw-overlay-scrim` (missing from compile-tokens.js's `groups` array)
    // would render as, with zero other test failure.
    const backdrop = await fallback.evaluate((el) => getComputedStyle(el).backgroundColor);
    expect(backdrop, 'the modal backdrop must resolve to a real color, not a dropped/transparent scrim').not.toBe(
      'rgba(0, 0, 0, 0)',
    );
    expect(backdrop).not.toBe('transparent');

    // Non-vacuity: the rendered markup is the REAL committed generator output,
    // not a hand-written stand-in that happens to carry the same data attribute.
    const componentSource = await page.request
      .get('/crosswake/tokens.css')
      .then((r) => r.text());
    expect(componentSource, 'the library-served tokens.css must carry the new scrim token').toContain(
      '--cw-overlay-scrim',
    );
  });

  test('the committed generated component carries the generator stamp (non-vacuity)', async ({ request }) => {
    // Read the committed file through Playwright's own process, not the browser —
    // this proves the file ON DISK (what the route actually renders from) is real
    // generator output, per D-46's non-vacuity condition for the absent/present pair.
    const fs = await import('node:fs');
    const path = await import('node:path');
    const componentPath = path.join(process.cwd(), GENERATED_COMPONENT_PATH);
    const source = fs.readFileSync(componentPath, 'utf8');

    expect(source, 'the committed component must carry the FALL-01 provenance stamp').toContain(
      'crosswake:native-controls-ui',
    );
    expect(source).toContain('template_version=1');
  });
});

// ---------------------------------------------------------------------------
// Helpers — self-sufficient setup, mirroring evidence_panel.spec.ts's house
// style rather than assuming a hand-seeded server.
// ---------------------------------------------------------------------------

async function resetShowcase(page: Page) {
  const reset = await page.request.post('/_e2e/showcase-reset');
  expect(reset.ok(), 'deterministic showcase reset must succeed').toBe(true);
}

async function asApprover(page: Page) {
  const session = await page.request.post('/_e2e/saas-session', { data: { user_id: 'approver-1' } });
  expect(session.ok(), 'approver-1 e2e session helper must succeed').toBe(true);
}
