defmodule Mix.Tasks.Crosswake.Gen.NativeControlsUi do
  @moduledoc """
  Generates host-owned, brand-tokenized native-controls fallback UI.

  Copies exactly two files, verbatim from library templates, into the target
  Phoenix host:

    * `lib/<app>_web/components/crosswake_fallbacks.ex` — a `Phoenix.Component`
      module carrying `confirm_modal/1`
    * `priv/static/assets/crosswake_fallback.css` — its stylesheet, a scoped
      `--cwfb-*` alias layer over the library's `--cw-*` tokens

  ## Why this ships as a generator, not an importable module

  `Crosswake.ComponentTierGuard` (Phase 155) statically forbids any
  `Phoenix.Component`/`~H`/`attr`/`slot` usage anywhere under `lib/` in this
  package. Presentation adopters restyle is a generator concern, never an
  importable-tier concern — the same rule that already governs
  `mix crosswake.gen.offline_ui` and `mix crosswake.gen.bridge_hook`.

  ## The confirm modal has no native counterpart, and never will

  `REQUIREMENTS.md` places a native alert/confirm bridge family permanently
  out of scope. The generated `confirm_modal/1` is not a fallback that
  degrades from something better — it is the primary, only, permanent confirm
  surface on every platform. It makes zero `Crosswake.Bridge` calls: no push,
  no `ref`, no `resolve/2`, no denial branch.

  If you can offer undo instead of asking "are you sure?", offer undo instead
  of this modal (Nielsen Norman Group).

  ## No-clobber, stamped provenance

  Re-running this task never overwrites either file — each existing file is
  reported as skipped, and re-running it after deleting only one file copies
  back just the missing one. There is no `--force` and no three-way merge.
  Both written files carry a `crosswake:native-controls-ui` provenance stamp
  naming the template version they were copied from
  (`mix crosswake.gen.bridge_hook`'s stamp shape). You own both files outright
  from the moment they are written — Crosswake will never rewrite them.

  ## Usage

      mix crosswake.gen.native_controls_ui
      mix crosswake.gen.native_controls_ui --app MyApp --dir /path/to/host

  ## Options

    * `--app` — the target application module name (defaults to auto-detect)
    * `--dir` — the target host directory (defaults to the current directory)
  """
  use Mix.Task

  @shortdoc "Generates host-owned, brand-tokenized native-controls fallback UI (confirm modal)"

  @switches [dir: :string, app: :string]

  @template_dir "priv/templates/crosswake/native_controls_ui"
  @component_template "crosswake_fallbacks.ex.eex"
  @stylesheet_template "crosswake_fallback.css.eex"

  @template_version 1

  @stamp_slug "crosswake:native-controls-ui"

  @impl Mix.Task
  def run(args) do
    {opts, _argv, invalid} = OptionParser.parse(args, strict: @switches)

    if invalid != [] do
      Mix.raise("invalid options: #{inspect(invalid)}")
    end

    app_module = opts[:app] || get_app_module()
    app_snake = Macro.underscore(app_module)

    dir = Path.expand(opts[:dir] || File.cwd!())
    web_dir = Path.join([dir, "lib", "#{app_snake}_web"])

    component_dest = Path.join([web_dir, "components", "crosswake_fallbacks.ex"])
    stylesheet_dest = Path.join([dir, "priv", "static", "assets", "crosswake_fallback.css"])

    assert_within_dir!(dir, component_dest)
    assert_within_dir!(dir, stylesheet_dest)

    component_content =
      stamp(:ex) <> EEx.eval_file(get_template_path(@component_template), app_module: app_module)

    stylesheet_content = stamp(:css) <> EEx.eval_file(get_template_path(@stylesheet_template), [])

    component_result = ensure_file(component_dest, component_content)
    stylesheet_result = ensure_file(stylesheet_dest, stylesheet_content)

    print_next_steps(app_module, component_dest, stylesheet_dest, component_result, stylesheet_result)
  end

  @doc false
  @spec template_version() :: pos_integer()
  def template_version, do: @template_version

  @doc """
  The stamp slug both generated files' provenance header contains, so
  `mix crosswake.doctor` can regex-parse either file's stamp identically. The
  Elixir file carries it behind a `# ` line comment; the CSS file behind a
  `/* ... */` block comment — the slug itself is comment-syntax-agnostic.
  """
  @spec stamp_prefix() :: String.t()
  def stamp_prefix, do: @stamp_slug

  # ---------------------------------------------------------------------------
  # Stamps
  # ---------------------------------------------------------------------------

  defp stamp(:ex) do
    """
    # #{@stamp_slug} template_version=#{@template_version}
    #
    # Host-owned copy generated by `mix crosswake.gen.native_controls_ui`.
    # You own this file outright: Crosswake will never rewrite it, and
    # re-running the generator reuses it rather than clobbering it.

    """
  end

  defp stamp(:css) do
    """
    /* #{@stamp_slug} template_version=#{@template_version}
     *
     * Host-owned copy generated by `mix crosswake.gen.native_controls_ui`.
     * You own this file outright: Crosswake will never rewrite it, and
     * re-running the generator reuses it rather than clobbering it.
     */

    """
  end

  # ---------------------------------------------------------------------------
  # Filesystem
  # ---------------------------------------------------------------------------

  defp assert_within_dir!(dir, destination) do
    expanded_dir = Path.expand(dir)
    expanded_dest = Path.expand(destination)

    unless expanded_dest == expanded_dir or String.starts_with?(expanded_dest, expanded_dir <> "/") do
      Mix.raise(
        "refusing to write outside the target directory: #{expanded_dest} is not under #{expanded_dir}"
      )
    end
  end

  defp ensure_file(path, contents) do
    case File.read(path) do
      {:ok, _existing} ->
        Mix.shell().info(
          "  reused #{relative_path(path)} (host-owned; the generator never clobbers your copy)"
        )

        :reused

      {:error, :enoent} ->
        write_new_file(path, contents)

      {:error, reason} ->
        Mix.raise("could not read #{path}: #{:file.format_error(reason)}")
    end
  end

  defp write_new_file(path, contents) do
    case File.mkdir_p(Path.dirname(path)) do
      :ok ->
        case File.write(path, contents) do
          :ok ->
            Mix.shell().info(
              "  created #{relative_path(path)} (template_version=#{@template_version})"
            )

            :created

          {:error, reason} ->
            Mix.raise("could not write #{path}: #{:file.format_error(reason)}")
        end

      {:error, reason} ->
        Mix.raise(
          "could not create directory #{Path.dirname(path)}: #{:file.format_error(reason)}"
        )
    end
  end

  defp relative_path(path) do
    case File.cwd() do
      {:ok, cwd} -> Path.relative_to(path, cwd)
      _ -> path
    end
  end

  defp get_template_path(filename) do
    path = Application.app_dir(:crosswake, Path.join(@template_dir, filename))

    if File.exists?(path) do
      path
    else
      Path.join(File.cwd!(), Path.join(@template_dir, filename))
    end
  end

  defp get_app_module do
    case Mix.Project.config()[:app] do
      nil -> "MyApp"
      app -> app |> to_string() |> Macro.camelize()
    end
  end

  # ---------------------------------------------------------------------------
  # Printed output (D-06 — the biggest DX number in this phase)
  # ---------------------------------------------------------------------------

  defp print_next_steps(app_module, component_dest, stylesheet_dest, component_result, stylesheet_result) do
    Mix.shell().info("""

    Native-controls fallback UI:
      #{result_word(component_result)} #{relative_path(component_dest)}
      #{result_word(stylesheet_result)} #{relative_path(stylesheet_dest)}

    Both files are yours now. Crosswake will never rewrite them; re-running
    this generator only fills in whichever one is missing.

    1. Link the stylesheet in your root layout, alongside the library-served
       tokens.css:

           <link rel="stylesheet" href="/assets/crosswake_fallback.css" />

    2. Render the confirm modal from a snapshot assign in the LiveView that
       needs it:

           <#{app_module}Web.CrosswakeFallbacks.confirm_modal
             id="my-confirm"
             open={@confirm_open}
             title="Approve this request?"
             body="The requester is notified and the decision is recorded."
             confirm_label="Approve request"
           />

    3. Paste these three handle_event clauses into that same LiveView, then
       fill in the mutation the confirm button should run:

           def handle_event("crosswake_fallback_answer", %{"answer" => "confirm"}, socket) do
             # TODO: run the mutation this confirm modal is guarding.
             {:noreply, assign(socket, confirm_open: false)}
           end

           def handle_event("crosswake_fallback_dismiss", _params, socket) do
             {:noreply, assign(socket, confirm_open: false)}
           end

           def handle_event("crosswake_fallback_answer", _params, socket) do
             {:noreply, socket}
           end

    This is the control you reach for when you are looking for a native
    confirm dialog and Crosswake doesn't have one — it never will (there is
    no native alert/confirm bridge family; see REQUIREMENTS.md).

    If you can offer undo instead of asking "are you sure?", offer undo instead of this modal.
    """)
  end

  defp result_word(:created), do: "created"
  defp result_word(:reused), do: "reused "
end
