defmodule Mix.Tasks.Crosswake.Gen.ShellStampTest do
  @moduledoc """
  Generated-output stamp coverage test for LIFE-02a (REVIEW FIX finding 4).

  Generates both iOS and Android shells into a tmp dir and asserts:
  - Every generated comment-supporting file carries the "Generated by crosswake" stamp.
  - The three D-02 stamp exclusions (project.pbxproj, gradlew, gradlew.bat) do NOT carry a stamp.
  - gradle.properties IS stamped (regression guard for review finding 4 correction (a)).
  - README.md files are NOT stamped (generated from shell_readme/1 string literal, not .eex).

  Mix task invocation is process-global, so these generator assertions must run serially.
  """

  use ExUnit.Case, async: false

  import ExUnit.CaptureIO

  @task "crosswake.gen.shell"
  @stamp_marker "Generated by crosswake"

  # Stamp-eligible files derived from @ios_templates + @android_templates minus D-02 exclusions.
  # These are the OUTPUT paths (relative to crosswake_shell root) of files that MUST carry a stamp.
  @ios_stamped_relative_paths [
    "CrosswakeShell/CrosswakeShellApp.swift",
    "CrosswakeShell/Info.plist",
    "CrosswakeShell/CrosswakeCoordinator.swift",
    "CrosswakeShell.xcodeproj/xcshareddata/xcschemes/CrosswakeShell.xcscheme",
    "CrosswakeShell/CrosswakeShell.entitlements",
    "CrosswakeShell/PrivacyInfo.xcprivacy"
  ]

  @android_stamped_relative_paths [
    "settings.gradle",
    "build.gradle",
    "gradle.properties",
    "gradle/wrapper/gradle-wrapper.properties",
    "app/build.gradle",
    "app/src/main/AndroidManifest.xml",
    "app/src/main/java/dev/crosswake/shell/MainActivity.kt",
    "app/src/main/java/dev/crosswake/shell/CrosswakeViewModel.kt",
    "app/src/main/res/values/themes.xml"
  ]

  # D-02 stamp exclusions: these MUST NOT carry a stamp.
  @ios_excluded_relative_paths [
    "CrosswakeShell.xcodeproj/project.pbxproj"
  ]

  @android_excluded_relative_paths [
    "gradlew",
    "gradlew.bat"
  ]

  test "all iOS stamp-eligible generated files carry the provenance stamp" do
    target = tmp_dir!("stamp-ios")

    capture_io(fn ->
      Mix.Task.reenable(@task)
      Mix.Task.run(@task, ["ios", "--target", target])
    end)

    ios_root = Path.join(target, "native/ios/crosswake_shell")

    for relative_path <- @ios_stamped_relative_paths do
      file_path = Path.join(ios_root, relative_path)
      contents = File.read!(file_path)

      assert contents =~ @stamp_marker,
             "Expected stamp '#{@stamp_marker}' in iOS generated file: #{relative_path}\n" <>
               "First 200 bytes: #{String.slice(contents, 0, 200)}"
    end
  end

  test "all Android stamp-eligible generated files carry the provenance stamp" do
    target = tmp_dir!("stamp-android")

    capture_io(fn ->
      Mix.Task.reenable(@task)
      Mix.Task.run(@task, ["android", "--target", target])
    end)

    android_root = Path.join(target, "native/android/crosswake_shell")

    for relative_path <- @android_stamped_relative_paths do
      file_path = Path.join(android_root, relative_path)
      contents = File.read!(file_path)

      assert contents =~ @stamp_marker,
             "Expected stamp '#{@stamp_marker}' in Android generated file: #{relative_path}\n" <>
               "First 200 bytes: #{String.slice(contents, 0, 200)}"
    end
  end

  test "gradle.properties is stamped (regression guard for review finding 4a)" do
    target = tmp_dir!("stamp-gradle-props")

    capture_io(fn ->
      Mix.Task.reenable(@task)
      Mix.Task.run(@task, ["android", "--target", target])
    end)

    android_root = Path.join(target, "native/android/crosswake_shell")
    props_path = Path.join(android_root, "gradle.properties")
    contents = File.read!(props_path)

    assert contents =~ "# Generated by crosswake",
           "Expected '# Generated by crosswake' stamp in gradle.properties\n" <>
             "Contents: #{contents}"
  end

  test "D-02 stamp exclusions (project.pbxproj, gradlew, gradlew.bat) do NOT carry a stamp" do
    ios_target = tmp_dir!("stamp-excl-ios")
    android_target = tmp_dir!("stamp-excl-android")

    capture_io(fn ->
      Mix.Task.reenable(@task)
      Mix.Task.run(@task, ["ios", "--target", ios_target])
    end)

    capture_io(fn ->
      Mix.Task.reenable(@task)
      Mix.Task.run(@task, ["android", "--target", android_target])
    end)

    ios_root = Path.join(ios_target, "native/ios/crosswake_shell")
    android_root = Path.join(android_target, "native/android/crosswake_shell")

    for relative_path <- @ios_excluded_relative_paths do
      file_path = Path.join(ios_root, relative_path)
      contents = File.read!(file_path)

      refute contents =~ @stamp_marker,
             "iOS exclusion file should NOT carry stamp: #{relative_path}"
    end

    for relative_path <- @android_excluded_relative_paths do
      file_path = Path.join(android_root, relative_path)
      contents = File.read!(file_path)

      refute contents =~ @stamp_marker,
             "Android exclusion file should NOT carry stamp: #{relative_path}"
    end
  end

  test "stamp includes template_version number" do
    target = tmp_dir!("stamp-version")

    capture_io(fn ->
      Mix.Task.reenable(@task)
      Mix.Task.run(@task, ["android", "--target", target])
    end)

    android_root = Path.join(target, "native/android/crosswake_shell")

    main_activity =
      Path.join(android_root, "app/src/main/java/dev/crosswake/shell/MainActivity.kt")

    contents = File.read!(main_activity)

    assert contents =~ "(template_version:",
           "Expected '(template_version:' in stamp line of MainActivity.kt"
  end

  defp tmp_dir!(prefix) do
    path = Path.join(System.tmp_dir!(), "#{prefix}-#{System.unique_integer([:positive])}")
    File.rm_rf!(path)
    File.mkdir_p!(path)
    path
  end
end
