defmodule Crosswake.Contract.ContractDriftTest do
  use ExUnit.Case, async: true

  # Canonical version source — THE authoritative value this test guards against.
  # Never use a literal "1.1.0" here; always read from the canonical Elixir function
  # so the test stays drift-proof as the contract version is bumped.
  @canonical_version Crosswake.Bridge.Contract.version()

  # ---------------------------------------------------------------------------
  # Surface lists (committed source paths only — do NOT read build/ or
  # .claude/worktrees/ copies per GUARD-01 prohibition D-03)
  # ---------------------------------------------------------------------------

  # PRIMARY surfaces: hand-maintained crosswake_manifest.json files.
  # bridge_protocol_version lives at ["compatibility"]["bridge_protocol_version"]
  # in these manifests (not the JSON document root). The manifests also carry
  # prose mentions of bridge_protocol_version at lines 1135+ inside
  # compatibility_signal / compatibility_contract strings — a text-grep would
  # falsely match those prose strings (GUARD-01 prohibition D-01, D-02).
  @manifest_paths [
    "examples/ios_shell_host/Fixtures/crosswake_manifest.json",
    "examples/android_shell_host/app/src/main/assets/crosswake_manifest.json"
  ]

  # TRIPWIRE surfaces: generated by `mix crosswake.contract.gen`.
  # bridge_protocol_version lives at the JSON document root for these files.
  #
  # NOTE: GUARD-02 (the generate-and-diff workflow in plan 03) is the canonical
  # source of truth for these three files — it byte-exactly regenerates them and
  # diffs against the committed copies. GUARD-01 asserts them here only as a fast,
  # friendly local tripwire for developer experience (DX): if you accidentally
  # hand-edit one, this test names the drifted file and tells you how to fix it,
  # without waiting for CI to run the full generate-and-diff lane.
  @generated_json_paths [
    "examples/ios_shell_host/Fixtures/route_activation.json",
    "examples/android_shell_host/app/src/main/assets/route_activation.json",
    "test/fixtures/bridge_contract_vectors.json",
    "packages/crosswake-shell-core-ios/Tests/CrosswakeShellCoreTests/Resources/bridge_contract_vectors.json",
    "packages/crosswake-shell-core-android/src/test/resources/bridge_contract_vectors.json"
  ]

  # DEV TRIPWIRE surfaces: generated by `mix crosswake.contract.gen --dev`.
  # These are committed dev fixtures that differ from prod only in url/origin.
  # Kept SEPARATE from @generated_json_paths so the prod "seven committed surfaces"
  # assertion is not affected (pitfall 7). Do NOT add these to @generated_json_paths.
  @dev_generated_json_paths [
    "examples/ios_shell_host/Fixtures/route_activation-dev.json",
    "examples/android_shell_host/app/src/dev/assets/route_activation.json"
  ]

  @all_surface_paths @manifest_paths ++ @generated_json_paths

  # ---------------------------------------------------------------------------
  # Readability / guard sanity test
  # ---------------------------------------------------------------------------

  test "readability: all seven committed surfaces exist and canonical version is semver" do
    assert @canonical_version =~ ~r/^\d+\.\d+\.\d+$/,
           "Crosswake.Bridge.Contract.version() must return a semver string; got: #{inspect(@canonical_version)}"

    for path <- @all_surface_paths do
      assert File.exists?(path),
             "Expected committed contract surface to exist: #{path}"
    end
  end

  # ---------------------------------------------------------------------------
  # Primary drift assertion
  # ---------------------------------------------------------------------------

  test "all committed contract surfaces carry the canonical bridge_protocol_version" do
    manifest_failures =
      Enum.flat_map(@manifest_paths, fn path ->
        path
        |> File.read!()
        |> Jason.decode!()
        |> compare_manifest_surface(path, @canonical_version)
      end)

    generated_failures =
      Enum.flat_map(@generated_json_paths, fn path ->
        path
        |> File.read!()
        |> Jason.decode!()
        |> compare_generated_surface(path, @canonical_version)
      end)

    assert_no_drift_failures(manifest_failures ++ generated_failures)
  end

  # ---------------------------------------------------------------------------
  # Dev fixture drift assertion
  #
  # Asserts that the two committed dev fixtures carry the canonical
  # bridge_protocol_version. The dev fixtures differ from prod only in url/origin
  # and _generated_by suffix — compare_generated_surface checks bridge_protocol_version
  # at the JSON root, so the --dev suffix in _generated_by is not a false positive.
  #
  # Because the dev fixtures are committed artifacts, the assertion is unconditional
  # — no File.exists? gating (D-13). A missing file surfaces as a read! error, not
  # a silent pass.
  # ---------------------------------------------------------------------------

  test "dev fixtures carry the canonical bridge_protocol_version" do
    generated_failures =
      Enum.flat_map(@dev_generated_json_paths, fn path ->
        path
        |> File.read!()
        |> Jason.decode!()
        |> compare_generated_surface(path, @canonical_version)
      end)

    assert_no_drift_failures(generated_failures)
  end

  # ---------------------------------------------------------------------------
  # Synthetic regression tests — prove the guard is non-vacuous (anti-vacuity)
  #
  # These tests feed deliberately drifted in-memory decoded JSON into the same
  # compare_* helpers used by the primary test and assert that the expected
  # failure categories are produced. This mirrors the synthetic-regression
  # idiom in native_evidence_drift_test.exs and quick_start_adoption_drift_test.exs.
  #
  # If these regressions pass with no failures produced, the guard is vacuous
  # (T-122-03 threat) — these tests catch that class of bug.
  # ---------------------------------------------------------------------------

  test "synthetic regression: manifest with wrong bridge_protocol_version produces :manifest_version_drift failure" do
    # A manifest-shaped decoded map with a deliberately wrong compatibility version.
    # In production the manifests carry this at ["compatibility"]["bridge_protocol_version"].
    drifted_manifest = %{
      "compatibility" => %{
        "bridge_protocol_version" => "0.9.0",
        "manifest_schema_version" => "1.0.0",
        "native_runtime_version" => "1.0.0"
      }
    }

    failures =
      compare_manifest_surface(
        drifted_manifest,
        "synthetic/crosswake_manifest.json",
        @canonical_version
      )

    assert Enum.any?(failures, &(&1.category == :manifest_version_drift)),
           "Expected a :manifest_version_drift failure from a manifest with a wrong bridge_protocol_version, got: #{inspect(failures)}"
  end

  test "synthetic regression: generated JSON with wrong bridge_protocol_version produces :generated_version_drift failure" do
    # A generated-JSON-shaped decoded map with a deliberately wrong top-level version.
    drifted_generated = %{
      "_generated_by" => "mix crosswake.contract.gen",
      "bridge_protocol_version" => "0.9.0",
      "protocol" => "crosswake.bridge"
    }

    failures =
      compare_generated_surface(
        drifted_generated,
        "synthetic/route_activation.json",
        @canonical_version
      )

    assert Enum.any?(failures, &(&1.category == :generated_version_drift)),
           "Expected a :generated_version_drift failure from generated JSON with a wrong bridge_protocol_version, got: #{inspect(failures)}"
  end

  test "failure message names canonical source, drifted surface, and fix command" do
    # Build a single drifted failure and render the message; assert the required
    # terms are present so the guard can never fall back to a bare ExUnit
    # left/right assertion that omits context.
    drifted_failure = %{
      path: "synthetic/crosswake_manifest.json",
      category: :manifest_version_drift,
      actual: "0.9.0",
      expected: @canonical_version
    }

    message = format_failure_message([drifted_failure])

    assert String.contains?(message, "mix crosswake.contract.gen"),
           "Failure message must name the fix command 'mix crosswake.contract.gen'"

    assert String.contains?(message, "lib/crosswake/bridge/contract.ex"),
           "Failure message must name the canonical source 'lib/crosswake/bridge/contract.ex'"

    assert String.contains?(message, "Crosswake.Bridge.Contract.version/0"),
           "Failure message must name the canonical function 'Crosswake.Bridge.Contract.version/0'"

    assert String.contains?(message, "synthetic/crosswake_manifest.json"),
           "Failure message must name the drifted surface path"

    assert String.contains?(message, "0.9.0"),
           "Failure message must include the actual (wrong) version"

    assert String.contains?(message, @canonical_version),
           "Failure message must include the canonical (expected) version"
  end

  # ---------------------------------------------------------------------------
  # Helpers — pure comparison (accept decoded maps so synthetic tests can feed
  # in-memory content without touching disk, mirroring the scan_surface idiom
  # from native_evidence_drift_test.exs)
  # ---------------------------------------------------------------------------

  # Extract bridge_protocol_version from a manifest's `compatibility` object
  # and compare. Using Jason.decode + key lookup — never a text grep — because
  # the manifests carry the literal token bridge_protocol_version inside
  # compatibility_signal and compatibility_contract prose strings at lines 1135+
  # that a String.contains? or regex scan would falsely match.
  defp compare_manifest_surface(decoded, path, expected) do
    actual = get_in(decoded, ["compatibility", "bridge_protocol_version"])

    if actual == expected do
      []
    else
      [
        %{
          path: path,
          category: :manifest_version_drift,
          actual: actual,
          expected: expected
        }
      ]
    end
  end

  # Extract bridge_protocol_version from the top-level JSON object for
  # generated fixtures and compare.
  defp compare_generated_surface(decoded, path, expected) do
    actual = decoded["bridge_protocol_version"]

    if actual == expected do
      []
    else
      [
        %{
          path: path,
          category: :generated_version_drift,
          actual: actual,
          expected: expected
        }
      ]
    end
  end

  defp assert_no_drift_failures([]), do: :ok

  defp assert_no_drift_failures(failures) do
    ExUnit.Assertions.flunk(format_failure_message(failures))
  end

  # Failure message follows the Crosswake house contract (D-12):
  #   - Header names the canonical source with its value
  #   - One line per drifted surface: path, actual vs expected
  #   - Trailing fix command
  defp format_failure_message(failures) do
    drifted_lines =
      Enum.map_join(failures, "\n", fn %{path: path, actual: actual, expected: expected} ->
        "  #{path}: bridge_protocol_version #{inspect(actual)} != expected #{inspect(expected)}"
      end)

    """
    Contract version drift detected.

    Canonical source: Crosswake.Bridge.Contract.version/0 at lib/crosswake/bridge/contract.ex
    Canonical value:  #{inspect(@canonical_version)}

    Drifted surfaces:
    #{drifted_lines}

    Fix: run mix crosswake.contract.gen and commit the regenerated surfaces.
    Hand-maintained manifests (crosswake_manifest.json) require manual updates.
    """
  end
end
