defmodule Crosswake.Contract.ContractDriftTest do
  use ExUnit.Case, async: true

  # Canonical version source — THE authoritative value this test guards against.
  # Never use a literal "1.1.0" here; always read from the canonical Elixir function
  # so the test stays drift-proof as the contract version is bumped.
  @canonical_version Crosswake.Bridge.Contract.version()

  # ---------------------------------------------------------------------------
  # Surface lists (committed source paths only — do NOT read build/ or
  # .claude/worktrees/ copies per GUARD-01 prohibition D-03)
  # ---------------------------------------------------------------------------

  # PRIMARY surfaces: hand-maintained crosswake_manifest.json files.
  # bridge_protocol_version lives at ["compatibility"]["bridge_protocol_version"]
  # in these manifests (not the JSON document root). The manifests also carry
  # prose mentions of bridge_protocol_version at lines 1135+ inside
  # compatibility_signal / compatibility_contract strings — a text-grep would
  # falsely match those prose strings (GUARD-01 prohibition D-01, D-02).
  @manifest_paths [
    "examples/ios_shell_host/Fixtures/crosswake_manifest.json",
    "examples/android_shell_host/app/src/main/assets/crosswake_manifest.json"
  ]

  # TRIPWIRE surfaces: generated by `mix crosswake.contract.gen`.
  # bridge_protocol_version lives at the JSON document root for these files.
  #
  # NOTE: GUARD-02 (the generate-and-diff workflow in plan 03) is the canonical
  # source of truth for these three files — it byte-exactly regenerates them and
  # diffs against the committed copies. GUARD-01 asserts them here only as a fast,
  # friendly local tripwire for developer experience (DX): if you accidentally
  # hand-edit one, this test names the drifted file and tells you how to fix it,
  # without waiting for CI to run the full generate-and-diff lane.
  @generated_json_paths [
    "examples/ios_shell_host/Fixtures/route_activation.json",
    "examples/android_shell_host/app/src/main/assets/route_activation.json",
    "test/fixtures/bridge_contract_vectors.json"
  ]

  @all_surface_paths @manifest_paths ++ @generated_json_paths

  # ---------------------------------------------------------------------------
  # Readability / guard sanity test
  # ---------------------------------------------------------------------------

  test "readability: all six committed surfaces exist and canonical version is semver" do
    assert @canonical_version =~ ~r/^\d+\.\d+\.\d+$/,
           "Crosswake.Bridge.Contract.version() must return a semver string; got: #{inspect(@canonical_version)}"

    for path <- @all_surface_paths do
      assert File.exists?(path),
             "Expected committed contract surface to exist: #{path}"
    end
  end

  # ---------------------------------------------------------------------------
  # Primary drift assertion
  # ---------------------------------------------------------------------------

  test "all committed contract surfaces carry the canonical bridge_protocol_version" do
    manifest_failures =
      Enum.flat_map(@manifest_paths, fn path ->
        path
        |> File.read!()
        |> Jason.decode!()
        |> compare_manifest_surface(path, @canonical_version)
      end)

    generated_failures =
      Enum.flat_map(@generated_json_paths, fn path ->
        path
        |> File.read!()
        |> Jason.decode!()
        |> compare_generated_surface(path, @canonical_version)
      end)

    assert_no_drift_failures(manifest_failures ++ generated_failures)
  end

  # ---------------------------------------------------------------------------
  # Helpers — pure comparison (accept decoded maps so synthetic tests can feed
  # in-memory content without touching disk, mirroring the scan_surface idiom
  # from native_evidence_drift_test.exs)
  # ---------------------------------------------------------------------------

  # Extract bridge_protocol_version from a manifest's `compatibility` object
  # and compare. Using Jason.decode + key lookup — never a text grep — because
  # the manifests carry the literal token bridge_protocol_version inside
  # compatibility_signal and compatibility_contract prose strings at lines 1135+
  # that a String.contains? or regex scan would falsely match.
  defp compare_manifest_surface(decoded, path, expected) do
    actual = get_in(decoded, ["compatibility", "bridge_protocol_version"])

    if actual == expected do
      []
    else
      [
        %{
          path: path,
          category: :manifest_version_drift,
          actual: actual,
          expected: expected
        }
      ]
    end
  end

  # Extract bridge_protocol_version from the top-level JSON object for
  # generated fixtures and compare.
  defp compare_generated_surface(decoded, path, expected) do
    actual = decoded["bridge_protocol_version"]

    if actual == expected do
      []
    else
      [
        %{
          path: path,
          category: :generated_version_drift,
          actual: actual,
          expected: expected
        }
      ]
    end
  end

  defp assert_no_drift_failures([]), do: :ok

  defp assert_no_drift_failures(failures) do
    ExUnit.Assertions.flunk(format_failure_message(failures))
  end

  # Failure message follows the Crosswake house contract (D-12):
  #   - Header names the canonical source with its value
  #   - One line per drifted surface: path, actual vs expected
  #   - Trailing fix command
  defp format_failure_message(failures) do
    drifted_lines =
      Enum.map_join(failures, "\n", fn %{path: path, actual: actual, expected: expected} ->
        "  #{path}: bridge_protocol_version #{inspect(actual)} != expected #{inspect(expected)}"
      end)

    """
    Contract version drift detected.

    Canonical source: Crosswake.Bridge.Contract.version/0 at lib/crosswake/bridge/contract.ex
    Canonical value:  #{inspect(@canonical_version)}

    Drifted surfaces:
    #{drifted_lines}

    Fix: run mix crosswake.contract.gen and commit the regenerated surfaces.
    Hand-maintained manifests (crosswake_manifest.json) require manual updates.
    """
  end
end
