defmodule <%= @policy_module %> do
  @moduledoc """
  Host-owned Crosswake policy entrypoint.

  Generated by `mix crosswake.install`. This file belongs to the host app after
  generation and is safe to edit as the route policy evolves.
  """

  @router <%= @router_module %>

  def router, do: @router

  def compile(opts \\ []) do
    Crosswake.Policy.Compiler.compile(@router, opts)
  end
end
